app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    //return redirect('id');
    return redirect('home');
    //return view('welcome');
});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
    	Route::post('auth', 'AuthAPIController@authenticate');
        Route::post('forgotPassword', 'AuthAPIController@forgot');
        Route::post('user/register', 'UserAPIController@register');
    	Route::group(['middleware' => ['jwt.auth']], function () {
            require config('infyom.laravel_generator.path.api_routes');
        });
    });
});



Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth']], function () {

    Route::get('fileupload', [
        'as' => 'fileupload',
        'uses' => 'Barryvdh\Elfinder\ElfinderController@showPopup',
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('paket', 'PaketController');
    });
    // tampilkan sesudah login









});



Route::get('petugas/cabang', 'PetugasController@cabang');

Route::resource('orders', 'OrdersController');
// catalog
Route::get('catalog/catalog', 'CatalogController@catalog');
Route::get('catalog/category', 'CatalogController@category');

Route::get('home', 'HomeController@index');


Route::resource('asset', 'AssetController');

Route::resource('category', 'CategoryController');
  Route::resource('post', 'PostController');



Route::resource('menu', 'MenuController');


Route::resource('transaction', 'TransactionController');

Route::resource('pointUser', 'PointUserController');

Route::resource('upload', 'UploadController');

Route::resource('shared', 'SharedController');
// Route::resource('stock', 'StockController');
Route::get('history', 'HistoryController@index');

Route::get('stock', 'StockController@index');
Route::get('stock/editstock', 'StockController@editstock');
Route::get('stock/deletestock', 'StockController@deletestock');
Route::get('stock/getcatalog', 'StockController@getcatalog');
Route::get('stock/getstock', 'StockController@getstock');
Route::get('stock/getcategori', 'StockController@getcategori');
Route::post('stock/store', 'StockController@store');
Route::get('stock/checkstock', 'StockController@checkstock');

Route::get('orders', 'OrdersController@index');
Route::get('member/draft', 'MemberController@draft');
Route::get('member', 'MemberController@index');
Route::post('member/draftcancel', 'MemberController@draftcancel');
Route::post('member/store', 'MemberController@store');
Route::post('member/hapus', 'MemberController@hapus');
Route::post('member/point', 'MemberController@point');
Route::get('member/statuspoint', 'MemberController@statuspoint');

//# transaksi member
Route::get('transaksi/getcatalog','TransaksiController@getcatalog'); 
Route::post('transaksi/simpandraf','TransaksiController@simpandraf'); 
Route::get('transaksi/itemedit','TransaksiController@itemedit'); 
Route::get('transaksi/detailitem','TransaksiController@detailitem'); 
Route::get('transaksi/cekmember','TransaksiController@cekmember'); 
Route::get('transaksi/totalbank','TransaksiController@totalbank');
Route::get('transaksi/latestmember','TransaksiController@latestmember'); 
Route::get('transaksi/memberview', 'TransaksiController@memberview');
Route::post('transaksi/member', 'TransaksiController@member');
Route::post('transaksi/delorderm', 'TransaksiController@delorderm');
Route::get('transaksi/updatemeja', 'TransaksiController@updatemeja');
Route::get('transaksi/keranjang', 'TransaksiController@keranjang');
Route::get('transaksi/plusorder', 'TransaksiController@plusorder');
Route::get('transaksi/minusorder', 'TransaksiController@minusorder');
Route::get('transaksi/delorder', 'TransaksiController@delorder');
Route::post('transaksi/createorder', 'TransaksiController@createorder');
Route::get('transaksi/detailproduk', 'TransaksiController@detailproduk');
Route::post('transaksi/updatenoted', 'TransaksiController@updatenoted');
Route::get('transaksi/orderbaru', 'TransaksiController@orderbaru');
Route::get('transaksi/history', 'TransaksiController@history');
Route::get('transaksi/printdata', 'TransaksiController@printdata');
Route::get('transaksi/printlap', 'TransaksiController@printlap');
Route::get('transaksi/printhistory', 'TransaksiController@printhistory');
Route::get('transaksi/chartr', 'TransaksiController@chartr');
Route::get('transaksi/chartcabang', 'TransaksiController@chartcabang');
Route::get('transaksi/chartfood', 'TransaksiController@chartfood');
Route::get('transaksi/getshared', 'TransaksiController@getshared');
Route::post('transaksi/createtransaksi', 'TransaksiController@createtransaksi');

Route::resource('cabang', 'BranchController');
Route::resource('petugas', 'PetugasController');
Route::resource('costumer', 'CostumerController');
Route::get('costumer/{id}/disable', 'CostumerController@disable');
Route::get('costumer/{id}/enable', 'CostumerController@enable');
Route::post('shared/send','SharedController@send'); 

app/Http/Controllers/CostumerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Repositories\UserRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use DB;
use Auth;
use Hash;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Routing\UrlGenerator;
use Config;
use File;


class CostumerController extends AppBaseController
{
    /** @var  OrderRepository */
 
    private $userRepository;
    protected $url;

    public function __construct(UserRepository $userRepo,UrlGenerator $url)
    {
         $this->userRepository = $userRepo;
         $this->url = $url;
    }


    public function index(Request $request)
   {

      $costumer = DB::table('users as a')->select('a.id','a.photo','a.name','a.email','a.phone','a.status','a.point','a.type')->where('type', '<>', 'petugas')->where('type', '<>', 'admin')->paginate(10);

       return view('costumer.index')->with(['costumer' => $costumer ]);


   }
   
   public function disable($id,Request $request)
   {
      
      DB::table('users')->where('id',$id)->update(['status'=>'0']);
       Flash::success('Costumer berhasil di nonaktifkan'); 
      return redirect(url('costumer')); 
   }

   public function enable($id,Request $request){

     
      DB::table('users')->where('id',$id)->update(['status'=>'1']);
         Flash::success('Costumer berhasil di aktifkan kembali');
          return redirect(url('costumer')); 
   }


    public function create(Request $request)
    {

           

    }

    public function store(CreateUserRequest $request)
    {
      
       
    }

    public function show($id,Request $request)
    {
      
        $user = DB::table('users as a')->select('a.id','a.address','a.photo','a.name','a.phone','a.email','a.religion','a.birthday','a.created_at','a.status')->where('a.id',$id)->get();

       


        if (empty($user[0])) {
            Flash::error('Costumer Kosong');
            return redirect(url('costumer'));  
        }

      
          return view('petugas.show')->with(['petugas'=> $user,'dates'=> $this->convert($user[0]->birthday),'create'=>$this->created($user[0]->created_at)]);
    }

    public function edit($id,Request $request)
    {

        

    }

    public function update($id, UpdateUserRequest $request)
    {

      


    }


    public function destroy($id,Request $request)
    {

       $user = $this->userRepository->findWithoutFail($id);
         
        
        if (empty($user)) {
            Flash::error('Costumer Kosong');

             return redirect(url('costumer'));
        }
        
        
          if(!empty($user->photo))
          {
            $file_gambar  =   $this->url->to(''.$user->photo);  
            File::delete($file_gambar);
          }

    
        $this->userRepository->delete($id);
        Flash::success('Costumer Berhasil Dihapus');
        return redirect(url('costumer'));

    }



  public function convert($tgl, $hari_tampil = true)
  {
    $bulan  = array("Jan"
            , "Feb"
            , "Mar"
            , "Apr"
            , "Mei"
            , "Jun"
            , "Jul"
            , "Agu"
            , "Sep"
            , "Okt"
            , "Nov"
            , "Des");
    $hari = array("Senin"
            , "Selasa"
            , "Rabu"
            , "Kamis"
            , "Jum'at"
            , "Sabtu"
            , "Minggu");
    $tahun_split  = substr($tgl, 0, 4);
    $bulan_split  = substr($tgl, 5, 2);
    $hari_split   = substr($tgl, 8, 2);
    $tmpstamp   = mktime(0, 0, 0, $bulan_split, $hari_split, $tahun_split);
    $bulan_jadi   = $bulan[date("n", $tmpstamp)-1];
    $hari_jadi    = $hari[date("N", $tmpstamp)-1];
    if(!$hari_tampil)
    $hari_jadi="";
    return $hari_split." ".$bulan_jadi." ".$tahun_split;
  }


  public function created($tgl, $hari_tampil = true)
  {
    $bulan  = array("Jan"
            , "Feb"
            , "Mar"
            , "Apr"
            , "Mei"
            , "Jun"
            , "Jul"
            , "Agu"
            , "Sep"
            , "Okt"
            , "Nov"
            , "Des");
    $hari = array("Senin"
            , "Selasa"
            , "Rabu"
            , "Kamis"
            , "Jum'at"
            , "Sabtu"
            , "Minggu");
    $tahun_split  = substr($tgl, 0, 4);
    $bulan_split  = substr($tgl, 5, 2);
    $hari_split   = substr($tgl, 8, 2);
    $tmpstamp   = mktime(0, 0, 0, $bulan_split, $hari_split, $tahun_split);
    $bulan_jadi   = $bulan[date("n", $tmpstamp)-1];
    $hari_jadi    = $hari[date("N", $tmpstamp)-1];
    if(!$hari_tampil)
    $hari_jadi="";
    return $hari_jadi." ".$hari_split." ".$bulan_jadi." ".$tahun_split;
  }

    // end dipakai fix

   

   
    
   

   


   

   


    

   

    

   

    public function bayar(request $request)
    {
          

        $bayar = $request->get('duit');
          $total = $request->get('total'); 

          $tr =  number_format($bayar,0,'','.');
          $tot =  number_format($total,0,'','.');
          
          $kembali = $bayar-$total;
          $count =  number_format($kembali,0,'','.');
          $content = '';

              if($bayar > $total)
              {
                    $content  .= '<td class="cde"> Bayar </td> <td class="pull-left"> : </td> <td class="fer"> <input id="id_bayar" class="form-control" type="text" value="'. $bayar.'" name="bayar" disabled></td>
                               
                                ';

             }else if($total == $bayar){
             
                     $content  .= '<td class="cde"> Bayar </td> <td class="pull-left"> : </td> <td class="fer"> <input id="id_bayar" class="form-control" type="text" value="'. $bayar.'" name="bayar" disabled></td>
                               
                                ';
              }else{
               
                      $content  .= '<td class="cde"> Bayar </td> <td class="pull-left"> : </td> <td class="fer"> <input id="id_bayar" class="form-control" type="text" value="0" name="bayar" disabled></td>
                                
                                ';

              }  

                return $content;
    }

     public function total(request $request)
    {
          

        $bayar = $request->get('duit');
          $total = $request->get('total'); 

          $tr =  number_format($bayar,0,'','.');
          $tot =  number_format($total,0,'','.');
          
          $kembali = $bayar-$total;
          $count =  number_format($kembali,0,'','.');
          $content = '';

              if($bayar > $total)
              {
                    $content  .= '<td class="cde"> Total </td> <td class="pull-left"> : </td> <td class="fer"> <input id="tb" class="form-control" type="text" value="'. $total.'" name="total" disabled></td>
                               
                                ';

             }else if($total == $bayar){
             
                     $content  .= '<td class="cde"> Total </td> <td class="pull-left"> : </td> <td class="fer"> <input id="tb" class="form-control" type="text" value="'. $total.'" name="total" disabled></td>
                               
                                ';
              }else{
               
                      $content  .= '<td class="cde"> Total </td> <td class="pull-left"> : </td> <td class="fer"> <input id="tb" class="form-control" type="text" value="0" name="total" disabled></td>
                                
                                ';

              }  

                return $content;
    }


    public function getBayar(request $request)
    {
          
       $login = Auth::user();
       $bayar = DB::table('transaction')->where(['user_id'=>$login->id,'status'=>'0'])->first()->pay;
       return $bayar;
      
    }


    public function getCostumer(request $request)
    {
          
       $login = Auth::user();
       $order = DB::table('transaction')->where(['user_id'=>$login->id,'status'=>'0'])->first()->costumer_id;
       $costumer = DB::table('users')->where(['id'=>$order])->first()->name;

       return $costumer;
      
    }

    public function getCostumerID(request $request)
    {
          
       $login = Auth::user();
       $costumer_id = DB::table('transaction')->where(['user_id'=>$login->id,'status'=>'0'])->first()->costumer_id;

       return $costumer_id;
      
    }


       public function getCategoryID(request $request)
    {
            $login = Auth::user();
            $order = Order::where(['user_id'=>$login->id])->get();
            $status = "";
            foreach ($order as $row) 
            {
              
              if($row['status'] =="0")
              {
                 $status = Order::where(['user_id'=>$login->id,'status'=>'0'])->groupBy('category_id')->first()->category_id;
              }

            } 
           
            return $status;
    }

    

    public function listcatalog(request $request)
    {  
        $id = $request->get('id');
        $category = DB::table('category')->where('id',$id)->first()->name;
        $this->postRepository->pushCriteria(new CatalogCriteria($request));
        $catalog = $this->postRepository->findByField('category_id',$id);
        $kategori = DB::table('category')->orderBy('id','desc')->get();


        

        return view('kasir.catalog.index')
        ->with(['category'=>$category,'id'=>$id,'catalog'=>$catalog,'kategori'=>$kategori]);
      
    }

    




    
   
}

resources/views/costumer/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Petugas
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'petugas.store','enctype'=>'multipart/form-data']) !!}

                        @include('petugas.fields_create')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/costumer/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Petugas Edit
        </h1>
    </section>
    <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($petugas, ['route' => ['petugas.update', $petugas->id], 'method' => 'patch','enctype'=>'multipart/form-data']) !!}

                        @include('petugas.fields_edit')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
    </div>
@endsection

resources/views/costumer/fields_create.blade.php
<!-- Nama -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nama Lengkap:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('cabang', 'Cabang:') !!}
    <select name="cabang" id="cabang" class="selectpicker form-control">
      <option value="0">Pilih Cabang</option>
    @foreach($cabang as $cabang)
          
                    <option value="{!! $cabang->id !!}" >{!! $cabang->name !!}</option>
             
    @endforeach
    </select>
</div>



<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control',"placeholder" => "Email"]) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Telp:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control',"placeholder" => "Telp"]) !!}
</div>



<div class="form-group col-sm-6">
    {!! Form::label('religion', 'Agama:') !!}
    <select id="religion" name="religion" class="selectpicker form-control">
      <option value="Other">Pilih Agama</option>
      <option value="Islam">Islam</option>
      <option value="Nasrani">Nasrani</option>
      <option value="Katolik">Katolik</option>
      <option value="Budha">Budha</option>
      <option value="Hindu">Hindu</option>
      <option value="Konghucu">Konghucu</option>
       <option value="Other">Lain - lain</option>
    </select>
    
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('birthday', 'Tanggal Lahir:') !!}
    {!! Form::text('birthday', null, ['class' => 'form-control date']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Alamat:') !!}
    {!! Form::textarea('address', null, ['class' => 'form-control']) !!}
</div>




<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('photo', 'Photo:') !!}
    {!! Form::file('photo', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-12">
    {!! Form::label('status', 'Status:') !!}<br/>
    {{ Form::radio('status', 1, '') }} Aktif<br>
    {{ Form::radio('status', 0, '')  }} Tidak Aktif
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('petugas.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/costumer/fields_edit.blade.php
<!-- Nama -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nama Lengkap:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('cabang', 'Cabang:') !!}
    <select name="cabang" id="cabang" class="selectpicker form-control">
      <option value="0">Pilih Cabang</option>
    @foreach($cabang as $cabang)
            @if($petugas->cabang_id == $cabang->id)
                  <option value="{!! $cabang->id !!}" selected>{!! $cabang->name !!}</option>
              @else
                    <option value="{!! $cabang->id !!}" >{!! $cabang->name !!}</option>
              @endif
    @endforeach
    </select>
</div>



<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control',"placeholder" => "Email"]) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Telp:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control',"placeholder" => "Telp"]) !!}
</div>



<div class="form-group col-sm-6">
    {!! Form::label('religion', 'Agama:') !!}
    <select id="religion" name="religion" class="selectpicker form-control">
      <option value="Other">Pilih Agama</option>
        @if($petugas->religion !="")
            <option value="{!! $petugas->religion !!}" selected="">{!! $petugas->religion !!}</option>
        @else
            <option value="Islam">Islam</option>
      <option value="Nasrani">Nasrani</option>
      <option value="Katolik">Katolik</option>
      <option value="Budha">Budha</option>
      <option value="Hindu">Hindu</option>
      <option value="Konghucu">Konghucu</option>
       <option value="Other">Lain - lain</option>
        @endif

      
    </select>
    
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('birthday', 'Tanggal Lahir:') !!}
    {!! Form::text('birthday', null, ['class' => 'form-control date']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Alamat:') !!}
    {!! Form::textarea('address', null, ['class' => 'form-control']) !!}
</div>




<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('photo', 'Photo:') !!}
    {!! Form::file('photo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
  @if($petugas->photo !="")
  <img width="50" height="50" src="{!! $petugas->photo !!}">
  @endif
</div>

<!-- Status Field -->
<div class="form-group col-sm-12">
    {!! Form::label('status', 'Status:') !!}<br/>
    {{ Form::radio('status', 1, isset($petugas) ? $petugas->status == 1 : false) }} Aktif<br>
    {{ Form::radio('status', 0, isset($petugas) ? $petugas->status == 0 : true) }} Tidak Aktif
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('petugas.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/costumer/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Costumer</h1>
        <h1 class="pull-right">
           
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                @if($costumer->isEmpty())
                    <div class="text-center">No Artis found.</div>
                @else
                     @include('costumer.table')

                {{ $costumer->links() }}
                
                @endif
                    
            </div>
        </div>
    </div>
@endsection

resources/views/costumer/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Petugas Detail
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('petugas.show_fields')
                    <a href="{!! route('petugas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/costumer/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Kode petugas:') !!}
    <p>{!! $petugas[0]->id !!}</p>
</div>

<!-- Discount Field -->
<div class="form-group">
    {!! Form::label('photo', 'Photo:') !!}
    <p><img width="100" height="100" src="{!! $petugas[0]->photo !!}" ></p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('name', 'Nama Lengkap:') !!}
    <p>{!! $petugas[0]->name !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('cabang', 'Cabang:') !!}
    <p>{!! $petugas[0]->cabang !!}</p>
</div>

<!-- Post Id Field -->
<div class="form-group">
    {!! Form::label('phone', 'Telp:') !!}
    <p>{!! $petugas[0]->phone !!}</p>
</div>

<!-- Code Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $petugas[0]->email !!}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('religion', 'Agama:') !!}
    <p>{!! $petugas[0]->religion !!}</p>
</div>

<!-- Qty Field -->
<div class="form-group">
    {!! Form::label('brithday', 'Tanggal Lahir:') !!}
    <p>{!! $dates !!}</p>
</div>

<!-- Qty Field -->
<div class="form-group">
    {!! Form::label('address', 'Alamat:') !!}
    <p>{!! $petugas[0]->address !!}</p>
</div>




<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>@if($petugas[0]->status =="0") Tidak Aktif @else Aktif @endif</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Dibuat:') !!}
    <p>{!! $create !!}</p>
</div>

resources/views/costumer/table.blade.php
<table class="table table-responsive" id="penjualan-table">
    <thead>
        <th>Photo</th>
        <th>Nama Lengkap</th>
        <th>Email</th>
        <th>Telp</th>
        <th>Poin</th>
        <th>Type</th>
        <th>Status</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($costumer as $row)
        <tr>
           <td><img width="50" height="50" src="{!! $row->photo !!}"></td> 
                 
            <td>{!! $row->name !!}</td> 
            <td>{!! $row->email !!}</td> 
            <td>{!! $row->phone !!}</td> 
            <td>{!! $row->point !!}</td> 
            <td>{!! $row->type !!}</td> 
            <td>@if($row->status =="0" ) Tidak Aktif @else Aktif @endif</td>
            <td>
                     {!! Form::open(['route' => ['costumer.destroy', $row->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('costumer.show', [$row->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        @if($row->status =="0")
                             <a href="{!! url('costumer/'.$row->id.'/enable') !!}" class='btn btn-default btn-xs'><i class="fa fa-check"></i></a>
                        @else
                    <a href="{!! url('costumer/'.$row->id.'/disable') !!}" class='btn btn-default btn-xs'><i class="fa fa-times"></i></a>
                        @endif
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Apakah anda yakin?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>     
        </tr>        
    @endforeach
    </tbody>
</table>