app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    //return redirect('id');
    return redirect('home');
    //return view('welcome');
});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
    	Route::post('auth', 'AuthAPIController@authenticate');
        Route::post('forgotPassword', 'AuthAPIController@forgot');
        Route::post('user/register', 'UserAPIController@register');
    	Route::group(['middleware' => ['jwt.auth']], function () {
            require config('infyom.laravel_generator.path.api_routes');
        });
    });
});



Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth']], function () {

    Route::get('fileupload', [
        'as' => 'fileupload',
        'uses' => 'Barryvdh\Elfinder\ElfinderController@showPopup',
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('paket', 'PaketController');
    });
    // tampilkan sesudah login









});



Route::get('petugas/cabang', 'PetugasController@cabang');

Route::resource('orders', 'OrdersController');
// catalog
Route::get('catalog/catalog', 'CatalogController@catalog');
Route::get('catalog/category', 'CatalogController@category');

Route::get('home', 'HomeController@index');


Route::resource('asset', 'AssetController');

Route::resource('category', 'CategoryController');
  Route::resource('post', 'PostController');



Route::resource('menu', 'MenuController');


Route::resource('transaction', 'TransactionController');

Route::resource('pointUser', 'PointUserController');

Route::resource('upload', 'UploadController');

Route::resource('shared', 'SharedController');
// Route::resource('stock', 'StockController');
Route::get('history', 'HistoryController@index');

Route::get('stock', 'StockController@index');
Route::get('stock/editstock', 'StockController@editstock');
Route::get('stock/deletestock', 'StockController@deletestock');
Route::get('stock/getcatalog', 'StockController@getcatalog');
Route::get('stock/getstock', 'StockController@getstock');
Route::get('stock/getcategori', 'StockController@getcategori');
Route::post('stock/store', 'StockController@store');
Route::get('stock/checkstock', 'StockController@checkstock');

Route::get('orders', 'OrdersController@index');
Route::get('member/draft', 'MemberController@draft');
Route::get('member', 'MemberController@index');
Route::post('member/draftcancel', 'MemberController@draftcancel');
Route::post('member/store', 'MemberController@store');
Route::post('member/hapus', 'MemberController@hapus');
Route::post('member/point', 'MemberController@point');
Route::get('member/statuspoint', 'MemberController@statuspoint');

//# transaksi member
Route::get('transaksi/getcatalog','TransaksiController@getcatalog'); 
Route::post('transaksi/simpandraf','TransaksiController@simpandraf'); 
Route::get('transaksi/itemedit','TransaksiController@itemedit'); 
Route::get('transaksi/detailitem','TransaksiController@detailitem'); 
Route::get('transaksi/cekmember','TransaksiController@cekmember'); 
Route::get('transaksi/totalbank','TransaksiController@totalbank');
Route::get('transaksi/latestmember','TransaksiController@latestmember'); 
Route::get('transaksi/memberview', 'TransaksiController@memberview');
Route::post('transaksi/member', 'TransaksiController@member');
Route::post('transaksi/delorderm', 'TransaksiController@delorderm');
Route::get('transaksi/updatemeja', 'TransaksiController@updatemeja');
Route::get('transaksi/keranjang', 'TransaksiController@keranjang');
Route::get('transaksi/plusorder', 'TransaksiController@plusorder');
Route::get('transaksi/minusorder', 'TransaksiController@minusorder');
Route::get('transaksi/delorder', 'TransaksiController@delorder');
Route::post('transaksi/createorder', 'TransaksiController@createorder');
Route::get('transaksi/detailproduk', 'TransaksiController@detailproduk');
Route::post('transaksi/updatenoted', 'TransaksiController@updatenoted');
Route::get('transaksi/orderbaru', 'TransaksiController@orderbaru');
Route::get('transaksi/history', 'TransaksiController@history');
Route::get('transaksi/printdata', 'TransaksiController@printdata');
Route::get('transaksi/printlap', 'TransaksiController@printlap');
Route::get('transaksi/printhistory', 'TransaksiController@printhistory');
Route::get('transaksi/chartr', 'TransaksiController@chartr');
Route::get('transaksi/chartcabang', 'TransaksiController@chartcabang');
Route::get('transaksi/chartfood', 'TransaksiController@chartfood');
Route::get('transaksi/getshared', 'TransaksiController@getshared');
Route::post('transaksi/createtransaksi', 'TransaksiController@createtransaksi');

Route::resource('cabang', 'BranchController');
Route::resource('petugas', 'PetugasController');
Route::resource('costumer', 'CostumerController');
Route::get('costumer/{id}/disable', 'CostumerController@disable');
Route::get('costumer/{id}/enable', 'CostumerController@enable');
Route::post('shared/send','SharedController@send'); 

resources/views/transaction/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'transaction.store']) !!}

                        @include('transaction.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transaction/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($transaction, ['route' => ['transaction.update', $transaction->id], 'method' => 'patch']) !!}

                        @include('transaction.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
    </div>
@endsection

resources/views/transaction/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Costumer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('costumer_id', 'Costumer Id:') !!}
    {!! Form::number('costumer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Order Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order_id', 'Order Id:') !!}
    {!! Form::number('order_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Qty Field -->
<div class="form-group col-sm-6">
    {!! Form::label('qty', 'Qty:') !!}
    {!! Form::number('qty', null, ['class' => 'form-control']) !!}
</div>

<!-- Pay Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pay', 'Pay:') !!}
    {!! Form::number('pay', null, ['class' => 'form-control']) !!}
</div>

<!-- Total Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total', 'Total:') !!}
    {!! Form::number('total', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::number('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('transaction.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/transaction/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Transaction</h1>
        <h1 class="pull-right">
          
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('transaction.table')
            </div>
        </div>
    </div>
@endsection

resources/views/transaction/print.blade.php
tes

resources/views/transaction/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaction
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('transaction.show_fields')
                    <a href="{!! route('transaction.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transaction/show_fields.blade.php
<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'Server:') !!}
    <p>{!! $transaction->user->name !!}</p>
</div>

<!-- Costumer Id Field -->
<div class="form-group">
    {!! Form::label('costumer_id', 'Costumer Id:') !!}
    <p>
         <?php      
             $costumer =  DB::table('users')->where('id',$transaction->costumer_id)->first()->name;

             ?>   
             {!! $costumer !!}
      

    </p>
</div>

<!-- Order Id Field -->
<div class="form-group">
    {!! Form::label('order_id', 'Order Id:') !!}
    <p>
        {!! $transaction->order_id !!}
        <table class="table">
            <thead>
                <th><b>Product</b></td>
                <th><b>Qty</b></td>
                <th><b>Diskon</b></td>  
             </thead>
             <tbody>
                @foreach($order as $order)
                <tr>
                    <td>
                        <?php 
                        $post =  DB::table('post')->where('id',$order->post_id)->first()->title; 

                    ?>
                        {!! $post !!}
                </td>
                    <td>{!! $order->qty !!}</td>
                    <td>{!! $order->discount !!} %</td>
                 </tr>   
                @endforeach
               </tbody> 

               
         </table>   


    </p>
</div>



<!-- Pay Field -->
<div class="form-group">
    {!! Form::label('pay', 'Bayar:') !!}
    <p>
         <?php $pay = number_format($transaction->pay,0,'','.'); ?> 
              Rp  {!! $pay !!}

    </p>
</div>

<!-- Total Field -->
<div class="form-group">
    {!! Form::label('total', 'Total:') !!}
    <p>
          <?php $total = number_format($transaction->total,0,'','.'); ?> 

              Rp  {!! $total !!}

    </p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>
        @if($transaction->status =="0") Proses @else Terjual @endif

    </p>
</div>

resources/views/transaction/table.blade.php
<table class="table table-responsive" id="transaction-table">
    <thead>
        <th>Costumer</th>
        <th>ID Order</th>
        <th>Bayar</th>
        <th>Total</th>
        <th>Poin</th>
         <th>Server</th>
        <th>Status</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($transaction as $transaction)
        <tr>
            
            <td>
                <?php      
                    $costumer =  DB::table('users')->where('id',$transaction->costumer_id)->first()->name;

             ?>   
             {!! $costumer !!}
            </td>
            <td>{!! $transaction->order_id !!}</td>
            
            <td>
                 <?php $pay = number_format($transaction->pay,0,'','.'); ?> 
              Rp  {!! $pay !!}

            </td>
            <td> 
                <?php $total = number_format($transaction->total,0,'','.'); ?> 

              Rp  {!! $total !!}
            </td>
            <td>{!! $transaction->point !!} Poin</td>
            <td>{!! $transaction->user->name !!}</td>
            <td>@if($transaction->status =="0") Proses @else Terjual @endif</td>
            <td>
                {!! Form::open(['route' => ['transaction.destroy', $transaction->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('transaction.show', [$transaction->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>