app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    //return redirect('id');
    return redirect('home');
    //return view('welcome');
});

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
    	Route::post('auth', 'AuthAPIController@authenticate');
        Route::post('forgotPassword', 'AuthAPIController@forgot');
        Route::post('user/register', 'UserAPIController@register');
    	Route::group(['middleware' => ['jwt.auth']], function () {
            require config('infyom.laravel_generator.path.api_routes');
        });
    });
});



Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth']], function () {

    Route::get('fileupload', [
        'as' => 'fileupload',
        'uses' => 'Barryvdh\Elfinder\ElfinderController@showPopup',
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
    Route::resource('paket', 'PaketController');
    });
    // tampilkan sesudah login









});



Route::get('petugas/cabang', 'PetugasController@cabang');

Route::resource('orders', 'OrdersController');
// catalog
Route::get('catalog/catalog', 'CatalogController@catalog');
Route::get('catalog/category', 'CatalogController@category');

Route::get('home', 'HomeController@index');


Route::resource('asset', 'AssetController');

Route::resource('category', 'CategoryController');
  Route::resource('post', 'PostController');



Route::resource('menu', 'MenuController');


Route::resource('transaction', 'TransactionController');

Route::resource('pointUser', 'PointUserController');

Route::resource('upload', 'UploadController');

Route::resource('shared', 'SharedController');
// Route::resource('stock', 'StockController');
Route::get('history', 'HistoryController@index');

Route::get('stock', 'StockController@index');
Route::get('stock/editstock', 'StockController@editstock');
Route::get('stock/deletestock', 'StockController@deletestock');
Route::get('stock/getcatalog', 'StockController@getcatalog');
Route::get('stock/getstock', 'StockController@getstock');
Route::get('stock/getcategori', 'StockController@getcategori');
Route::post('stock/store', 'StockController@store');
Route::get('stock/checkstock', 'StockController@checkstock');

Route::get('orders', 'OrdersController@index');
Route::get('member/draft', 'MemberController@draft');
Route::get('member', 'MemberController@index');
Route::post('member/draftcancel', 'MemberController@draftcancel');
Route::post('member/store', 'MemberController@store');
Route::post('member/hapus', 'MemberController@hapus');
Route::post('member/point', 'MemberController@point');
Route::get('member/statuspoint', 'MemberController@statuspoint');

//# transaksi member
Route::get('transaksi/getcatalog','TransaksiController@getcatalog'); 
Route::post('transaksi/simpandraf','TransaksiController@simpandraf'); 
Route::get('transaksi/itemedit','TransaksiController@itemedit'); 
Route::get('transaksi/detailitem','TransaksiController@detailitem'); 
Route::get('transaksi/cekmember','TransaksiController@cekmember'); 
Route::get('transaksi/totalbank','TransaksiController@totalbank');
Route::get('transaksi/latestmember','TransaksiController@latestmember'); 
Route::get('transaksi/memberview', 'TransaksiController@memberview');
Route::post('transaksi/member', 'TransaksiController@member');
Route::post('transaksi/delorderm', 'TransaksiController@delorderm');
Route::get('transaksi/updatemeja', 'TransaksiController@updatemeja');
Route::get('transaksi/keranjang', 'TransaksiController@keranjang');
Route::get('transaksi/plusorder', 'TransaksiController@plusorder');
Route::get('transaksi/minusorder', 'TransaksiController@minusorder');
Route::get('transaksi/delorder', 'TransaksiController@delorder');
Route::post('transaksi/createorder', 'TransaksiController@createorder');
Route::get('transaksi/detailproduk', 'TransaksiController@detailproduk');
Route::post('transaksi/updatenoted', 'TransaksiController@updatenoted');
Route::get('transaksi/orderbaru', 'TransaksiController@orderbaru');
Route::get('transaksi/history', 'TransaksiController@history');
Route::get('transaksi/printdata', 'TransaksiController@printdata');
Route::get('transaksi/printlap', 'TransaksiController@printlap');
Route::get('transaksi/printhistory', 'TransaksiController@printhistory');
Route::get('transaksi/chartr', 'TransaksiController@chartr');
Route::get('transaksi/chartcabang', 'TransaksiController@chartcabang');
Route::get('transaksi/chartfood', 'TransaksiController@chartfood');
Route::get('transaksi/getshared', 'TransaksiController@getshared');
Route::post('transaksi/createtransaksi', 'TransaksiController@createtransaksi');

Route::resource('cabang', 'BranchController');
Route::resource('petugas', 'PetugasController');
Route::resource('costumer', 'CostumerController');
Route::get('costumer/{id}/disable', 'CostumerController@disable');
Route::get('costumer/{id}/enable', 'CostumerController@enable');
Route::post('shared/send','SharedController@send'); 

app/Models/Branch.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Branch",
 *      required={"client_id", "user_id", "name", "type", "status"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="client_id",
 *          description="client_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="user_id",
 *          description="user_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="type",
 *          description="type",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="status",
 *          description="status",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Branch extends Model
{
    //use SoftDeletes;

    public $table = 'branch';
    

    //protected $dates = ['deleted_at'];


    public $fillable = [
      
        'name',
        'user_id',
        'description',
        'telp',
        'latitude',
        'longitude',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
       
        'name' => 'string',
        'user_id' => 'integer',
        'description' => 'string',
        'telp' => 'string',
        'latitude'=> 'string',
        'longitude'=> 'string',
        'status' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
       
    ];

   

  
    
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreateBranchRequest;
use App\Http\Requests\UpdateBranchRequest;
use App\Repositories\BranchRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Criteria\BranchCriteria;
use Response;
use Auth;
use Illuminate\Routing\UrlGenerator;

class BranchController extends AppBaseController
{
    /** @var  BranchRepository */
    private $branchRepository;

    public function __construct(BranchRepository $branchRepo,UrlGenerator $url)
    {
        $this->branchRepository = $branchRepo;
        $this->url = $url;
    }

    /**
     * Display a listing of the Branch.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

            $user = Auth::user();
            $cari = $request->get('cari', null);

            $user = Auth::user();
        if(empty($user->id))
        {
           return redirect(url('login'));
        }
                //table Role
            $user_id = $user->id;
            $this->branchRepository->pushCriteria(new BranchCriteria($user_id));
            $this->branchRepository->pushCriteria(new RequestCriteria($request)); 
            $branch = $this->branchRepository->paginate(10);

            // search
             if ($cari!=null)
             {
              return redirect('branch/?search=name:'.$cari.'&searchFields=name:like');
      
             }


        return view('branch.index')
            ->with('branch', $branch);
    }

    /**
     * Show the form for creating a new Branch.
     *
     * @return Response
     */
    public function create()
    {

       

        return view('branch.create');
        
        

        
    }

    /**
     * Store a newly created Branch in storage.
     *
     * @param CreateBranchRequest $request
     *
     * @return Response
     */
    public function store(CreateBranchRequest $request)
    {
        $user = Auth::user();
        $user_id = $user->id;
        $input = $request->all();
        $input['user_id'] = $user_id;
        $branch = $this->branchRepository->create($input);

        Flash::success('Cabang berhasil disimpan.');

        return redirect(route('cabang.index'));
    }

    /**
     * Display the specified Branch.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $branch = $this->branchRepository->findWithoutFail($id);

        if (empty($branch)) {
            Flash::error('Cabang Kosong');

            return redirect(route('cabang.index'));
        }

        return view('branch.show')->with('branch', $branch);
    }

    /**
     * Show the form for editing the specified Branch.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $branch = $this->branchRepository->findWithoutFail($id);

        if (empty($branch)) {
            Flash::error('Cabang Kosong');

            return redirect(route('branch.index'));
        }

        return view('branch.edit')->with('branch', $branch);
    }

    /**
     * Update the specified Branch in storage.
     *
     * @param  int              $id
     * @param UpdateBranchRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBranchRequest $request)
    {
        $branch = $this->branchRepository->findWithoutFail($id);

        if (empty($branch)) {
            Flash::error('Branch not found');

            return redirect(route('cabang.index'));
        }

        $branch = $this->branchRepository->update($request->all(), $id);

        Flash::success('Cabang berhasil di update.');

       return redirect(route('cabang.index'));
    }

    /**
     * Remove the specified Branch from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $branch = $this->branchRepository->findWithoutFail($id);

        if (empty($branch)) {
            Flash::error('Cabang Kosong');

            return redirect(route('cabang.index'));
        }

        $this->branchRepository->delete($id);

        Flash::success('Cabang berhasil dihapus.');

        return redirect(route('cabang.index'));
    }
}

resources/views/branch/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
           Tambah Cabang
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'cabang.store']) !!}

                        @include('branch.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/branch/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
     
        <h1>Edit Cabang</h1>
     


   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($branch, ['route' => ['cabang.update', $branch->id], 'method' => 'patch']) !!}

                        @include('branch.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/branch/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>




<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('description', 'Alamat:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>



<style type="text/css">
#areamap {
    float: left;
    width: 100%;
}
.rowe {
    border-radius:3px;
    border: 1px solid #EAEAEA;
    background: #EAEAEA;
}
.center h2 {
   
    margin-top: 35px;
   
}
#areamap .koordinat {
    float: left;
    width: 100%;
    color: #FFF;
    font-weight: bold;
    background: none repeat scroll 0% 0% #313131;
    text-shadow: none;
}
#areamap .koordinat .pade {
    float: left;
    padding: 10px;
    width: 100%;
}

#areamap .koordinat {
    float: left;
    width: 100%;
    color: #FFF;
    font-weight: bold;
    background: none repeat scroll 0% 0% #313131;
    text-shadow: none;
}
#areamap .koordinat .pade .kiri {
width: 100%;
height: auto;
float: left;
margin: 0px 0px 14px;
}
#areamap .koordinat .pade .kananew {
   width: 100%;
    height: auto;
    float: left;
}


  </style>

<div class="form-group col-sm-12">

<div id="areamap">


<div class="koordinat">
    <div class="pade">
    Ancer - ancer / Denah Lokasi (Geser <strong>PETA</strong> atau <strong>TANDA PANAH MERAH</strong> ke lokasi yang tepat.<br>
    Perbesar peta (zoom) untuk tampilan peta yang lebih detail.)
    </div>
</div>

<div id="map_canvas" style="width:100%; height: 400px; position: relative; background-color: #E5E3DF; overflow: hidden;"></div>

 <div class="koordinat" style="margin-bottom:30px;"></div>


   

</div>

</div>
                            
                        
<script>
$(document).ready(function() {
    myMap();
});
var map;
var arrMarker = [];
var myLatlng;

function myMap() {
  myLatlng = new google.maps.LatLng(-7.791838134699915, 110.37154953652339);
  var myOptions = {
    center: myLatlng,
    zoom: 12,
    mapTypeId: google.maps.MapTypeId.ROADMAP
    
  }
   map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
    var styleOptions = {
            name: "Dummy Style"
        };
        
    var MAP_STYLE = [
        {
            featureType: "road",
            elementType: "all",
            stylers: [
                { visibility: "on" }
            ]
        }
    ];
     var mapType = new google.maps.StyledMapType(MAP_STYLE, styleOptions);

    map.mapTypes.set("Dummy Style", mapType);
    map.setMapTypeId("Dummy Style");  
    createPosition();
}
function createPosition(){
    marker1 = new google.maps.Marker({map : map,
                                        draggable: true,
                                        icon: '{!! asset('img/input.png') !!}',
                                        position: myLatlng});
    google.maps.event.addListener(marker1, 'dragend', function (event) {
    document.getElementById("latitude").value = this.getPosition().lat();
    document.getElementById("longitude").value = this.getPosition().lng();
    });

}


</script>


<script src="https://maps.googleapis.com/maps/api/js?sensor=false&language=id&key=AIzaSyDzC9NRcR-_gLQdcOGqAn4ayVtWWEXexzA&callback=myMap"></script>

<!-- Latitude Field -->
<div class="form-group col-sm-12">
    {!! Form::label('telp', 'Telp:') !!}
    {!! Form::text('telp', null, ['class' => 'form-control']) !!}
</div>

<!-- Latitude Field -->
<div class="form-group col-sm-12">
    {!! Form::label('latitude', 'Latitude:') !!}
    {!! Form::text('latitude', null, ['class' => 'form-control']) !!}
</div>

<!-- Longitude Field -->
<div class="form-group col-sm-12">
    {!! Form::label('longitude', 'Longitude:') !!}
    {!! Form::text('longitude', null, ['class' => 'form-control']) !!}
</div>




<!-- Status Field -->
<div class="form-group col-sm-12">
    {!! Form::label('status', 'Status:') !!}<br/>
    {{ Form::radio('status', 1, isset($branch) ? $branch->status == 1 : false) }} Yes<br>
    {{ Form::radio('status', 0, isset($branch) ? $branch->status == 0 : true) }} No
</div>






<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('cabang.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/branch/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
   
        <h1 class="pull-left">Cabang</h1>
   

        <h1 class="pull-right">
         
           <a class="btn btn-danger pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('cabang.create') !!}">Add New</a>
        
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
  <div class="box-header">
   
         <h3 class="box-title">Data Cabang</h3>
    

 
  <form class="navbar-form navbar-right" method="GET" >
  <div class="box-tools">
    <div class="input-group input-group-sm" style="width: 150px;">
      <input type="text" name="cari" class="form-control pull-right" placeholder="Search"  >
      
      <div class="input-group-btn">
        <button  type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </div>
  </form>

</div>              
     

                @if($branch->isEmpty())
                    <div class="text-center">No Artis found.</div>
                @else
                     @include('branch.table')

                {{ $branch->links() }}
                
                @endif

            </div>
        </div>
    </div>
@endsection

resources/views/branch/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Cabang
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('branch.show_fields')
                    <a href="{!! route('cabang.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/branch/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $branch->name !!}</p>
</div>



<!-- Name Field -->
<div class="form-group">
    {!! Form::label('description', 'Alamat:') !!}
    <p>{!! $branch->description !!}</p>
</div>
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('telp', 'Telp:') !!}
    <p>{!! $branch->telp !!}</p>
</div>


<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>@if($branch->status == "0") Tidak Aktif @else Aktif @endif</p>
</div>

resources/views/branch/table.blade.php
<div class="table-responsive">
<table class="table table-striped table-bordered table-hover" id="branch-table">
    <thead>
         <th>Nama Cabang</th>
        <th>Alamat</th>
         <th>Telp</th>
      
        <th>Status</th>
        <th colspan="3">Aksi</th>
    </thead>
    <tbody>
         
     @foreach($branch as $branch)
 
        <tr>
          
            <td>{!! $branch->name !!}</td>
          
            <td>{!! $branch->description !!}</td>
             <td>{!! $branch->telp !!}</td>
                       <td>
             @if($branch->status>0)
               Aktif
             @else
                Non Aktif
             @endif
               

            </td>
            <td>

                {!! Form::open(['route' => ['cabang.destroy', $branch->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('cabang.show', [$branch->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('cabang.edit', [$branch->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                   
                  
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Apakah anda yakin?')"]) !!}
                  
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
</div>